services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: vteam_user
      POSTGRES_PASSWORD: osay21
      POSTGRES_DB: vteam_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vteam_user -d vteam_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend/api
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - ./backend/api/.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/check || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    container_name: frontend-web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - HOST=0.0.0.0

#  bike-simulator:
#    ports:
#      - "8080:8080"
#    build: ./bike-simulator
#    container_name: bike-simulator
#    environment:
#      - BACKEND_URL=http://api:3000
#    depends_on:
#      - api
