services:
  api:
    build: ./backend/api
    container_name: api
    ports:
      - "3000:3000"
    env_file: ./backend/api/.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: vteam_user
      POSTGRES_PASSWORD: osay21
      POSTGRES_DB: vteam_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    container_name: frontend-web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    depends_on:
      - api

#  simulator:
#    build: ./bike-simulator
#    container_name: bike-simulator
#    depends_on: 
#      - api
#    environment:
#      BACKEND_URL: http://api:3000
#      WS_URL: ws://api:8080
#    restart: unless-stopped